services:
  - type: web
    name: services-com
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    pythonVersion: 3.12.6
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.6
